# Generated by Django 3.2.8 on 2021-11-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Phoneno',
            new_name='Phone_no',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email_id',
        ),
    ]
