# Generated by Django 3.2.8 on 2021-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.IntegerField(primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
