# Generated by Django 3.2.8 on 2021-11-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20211109_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_train',
            name='trevaltime',
        ),
        migrations.AddField(
            model_name='add_train',
            name='traveltime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='add_train',
            name='arrivaltime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='add_train',
            name='departuretime',
            field=models.TimeField(null=True),
        ),
    ]
